/************************************************************\
 **     Copyright (c) 2012-2023 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	D:/Chang/files/code/anlogic_verilog/Interface/demo_1st/01_src/03_ip/rst_BUFG.v
 ** Date	:	2024 12 20
 ** TD version	:	5.6.71036
\************************************************************/

`timescale 1ns / 1ps

module rst_BUFG ( i, o );
		output 		o;
		input  		i;

		EG_LOGIC_BUFG bufg(
		.i(i),
		.o(o));

endmodule