--------------------------------------------------------------
 --     Copyright (c) 2012-2023 Anlogic Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	D:/Chang/files/code/anlogic_verilog/Interface/demo_1st/01_src/03_ip/rst_BUFG.vhd
 -- Date	:	2024 12 20
 -- TD version	:	5.6.71036
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY eagle_macro;
	USE eagle_macro.EAGLE_COMPONENTS.all;

ENTITY rst_BUFG IS
PORT (
	i	: IN STD_LOGIC;
	o	: OUT STD_LOGIC
	);
END rst_BUFG;

ARCHITECTURE struct OF rst_BUFG IS

	BEGIN
	bufg : EG_LOGIC_BUFG
		PORT MAP (
			i	=> i,
			o	=> o
		);

END struct;
